name: 🚀 Feature or Improvement request
description: Suggest an idea for the DXcharts Lite
labels: ['enhancement: need to review']
body:
    - type: markdown
      attributes:
          value: |
              Please provide a searchable summary of the feature in the title.

              Thanks for contributing by requesting a feature! 🙏
    - type: checkboxes
      attributes:
          label: Duplicates
          description: Please [search the history](https://github.com/devexperts/dxcharts-lite/issues) to see if a feature was already proposed.
          options:
              - label: I have searched the proposed features
                required: true
    - type: checkboxes
      attributes:
          label: Latest version
          description: We roll bug fixes, performance enhancements, features and other improvements into new releases.
          options:
              - label: I have tested the latest version
                required: true

    - type: textarea
      id: suggestion_summary
      attributes:
          label: Suggestion ⭐
          description: "A summary of what you'd like to see added or changed"
      validations:
          required: true
    - type: textarea
      attributes:
          label: Motivation 🔦
          description: What are you trying to accomplish? How has the lack of this feature affected you? Providing context helps us come up with a solution that is more useful in the real world.
    - type: textarea
      attributes:
          label: Examples 📃
          description: Provide an example how the API should look like or any information that could help to describe the feature.
